name: Publish Any Commit
on:
  push: {}
#on:
#  push:
#    branches:
#      - main
#  issue_comment:
#    types: [created]

jobs:
  build:
#    if: github.repository == 'antfu-collective/ni' && (github.event_name == 'push' || github.event.issue.pull_request && startsWith(github.event.comment.body, '/pkg-pr-new'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Build
#        working-directory: .
        run: pnpm build

      - run: pnpm pkg-pr-new publish --compact --pnpm
#      - run: pnpm pkg-pr-new publish --compact --pnpm .
